<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>

  <name>REmatch</name>
  <description>The REmatch library for Java: A novel regex engine for finding all matches over
    documents.</description>
  <url>https://rematch.cl/</url>

  <groupId>cl.rematch</groupId>
  <artifactId>rematch</artifactId>
  <version>0.1.0</version>
  <packaging>jar</packaging>

  <licenses>
    <license>
      <name>MIT License</name>
      <url>https://opensource.org/license/mit</url>
      <distribution>repo</distribution>
    </license>
  </licenses>

  <developers>
    <developer>
      <name>Vicente Calisto</name>
    </developer>
    <developer>
      <name>Patricia Silva</name>
    </developer>
    <developer>
      <name>Gustavo Toro</name>
    </developer>
  </developers>

  <scm>
    <connection>scm:git:git://github.com/REmatchChile/REmatch-java.git</connection>
    <developerConnection>scm:git:ssh://github.com:REmatchChile/REmatch-java.git</developerConnection>
    <url>https://github.com/REmatchChile/REmatch-java</url>
  </scm>

  <prerequisites>
    <maven>3.9.9</maven>
  </prerequisites>

  <properties>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <build>
    <resources>
      <resource>
        <directory>src/main/resources</directory>
      </resource>
    </resources>

     <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-source-plugin</artifactId>
        <version>3.4.0</version>
        <executions>
          <execution>
            <id>attach-sources</id>
            <goals>
              <goal>jar-no-fork</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-gpg-plugin</artifactId>
        <version>3.2.8</version>
        <configuration>
          <useAgent>false</useAgent>
          <passphraseEnvName>MAVEN_GPG_PASSPHRASE</passphraseEnvName>
          <gpgArguments>
            <arg>--pinentry-mode</arg>
            <arg>loopback</arg>
          </gpgArguments>
        </configuration>
        <executions>
          <execution>
            <id>sign-artifacts</id>
            <phase>verify</phase>
            <goals>
              <goal>sign</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
        <version>3.12.0</version>
        <configuration>
          <excludePackageNames>
            cl.rematch.internal
          </excludePackageNames>
        </configuration>
        <executions>
          <execution>
            <id>attach-javadoc</id>
            <goals>
              <goal>jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>org.sonatype.central</groupId>
        <artifactId>central-publishing-maven-plugin</artifactId>
        <version>0.11.0</version>
        <extensions>true</extensions>
        <configuration>
          <publishingServerId>central</publishingServerId>
          <autoPublish>true</autoPublish>
          <waitUntil>uploaded</waitUntil>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <profiles>
    <profile>
      <id>linux</id>
      <activation>
        <os>
          <family>unix</family>
        </os>
      </activation>
      <build>
        <resources>
          <resource>
            <directory>${project.basedir}/build/classes</directory>
            <includes>
              <include>cl/rematch/internal/linux-x86_64/libjniREmatch.so</include>
            </includes>
          </resource>
        </resources>
      </build>
    </profile>

    <profile>
      <id>windows</id>
      <activation>
        <os>
          <family>Windows</family>
        </os>
      </activation>
      <build>
        <resources>
          <resource>
            <directory>${project.basedir}/build/classes</directory>
            <includes>
              <include>cl/rematch/internal/windows-x86_64/jniREmatch.dll</include>
            </includes>
          </resource>
            <resource>
              <directory>${project.basedir}/build/REmatch-install/bin</directory>
              <includes>
                <include>REmatch.dll</include>
              </includes>
              <targetPath>
                cl/rematch/internal/windows-x86_64
              </targetPath>
            </resource>
        </resources>
      </build>
    </profile>
  </profiles>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.junit</groupId>
        <artifactId>junit-bom</artifactId>
        <version>6.0.0</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>org.bytedeco</groupId>
      <artifactId>javacpp</artifactId>
      <version>1.5.13</version>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <version>6.1.2</version>
    </dependency>
  </dependencies>
</project>