<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>

  <groupId>cl.rematch</groupId>
  <artifactId>rematch</artifactId>
  <version>0.0.1-SNAPSHOT</version>

  <properties>
      <maven.compiler.source>17</maven.compiler.source>
      <maven.compiler.target>17</maven.compiler.target>
  </properties>

  <dependencies>
    <dependency>
        <groupId>org.bytedeco</groupId>
        <artifactId>javacpp</artifactId>
        <version>1.5.13</version>
    </dependency>
  </dependencies>

  <build>
    <resources>
        <resource>
            <directory>${project.basedir}/build/jni</directory>
            <includes>
                <include>libjniREmatch.so</include>
            </includes>
        </resource>

        <resource>
            <directory>src/main/resources</directory>
        </resource>
    </resources>
  </build>
</project>
