name: Debug
on:
  workflow_dispatch:

jobs:
  cpp:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04-arm, ubuntu-24.04]

    steps:
      - name: Environment
        run: |
          uname -a
          uname -m
          lscpu
          which c++
          c++ --version
          which gcc
          gcc --version
          which clang
          clang --version || true

      - name: Install Catch2
        run: |
          git clone https://github.com/catchorg/Catch2.git
          cmake -B Catch2/build \
            -S Catch2 \
            -DBUILD_TESTING=OFF
          sudo cmake --build Catch2/build --target install

      - name: Install REmatch
        run: |
          git clone https://github.com/REmatchChile/REmatch.git -b mvn
          cd REmatch
          cmake -Bbuild -S. \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_TESTING=ON \
            -DBUILD_SHARED_LIBS=ON \
            -DCMAKE_INSTALL_PREFIX="$RUNNER_TEMP/REmatch"

          cmake --build build --verbose
          cmake --install build

          echo "TESTS"
          ./build/bin/rematch-test

          echo "INSTALL DIR"
          find "$RUNNER_TEMP/REmatch" -print

          echo "LIBRARY"
          file "$RUNNER_TEMP/REmatch/lib/libREmatch.so"

          echo "ELF"
          readelf -h "$RUNNER_TEMP/REmatch/lib/libREmatch.so"

          echo "DEPENDENCIES"
          ldd "$RUNNER_TEMP/REmatch/lib/libREmatch.so"

  java:
    name: Java ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04-arm
          - ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Java
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Resolve Maven dependencies
        run: mvn dependency:resolve

      - name: Configure CMake
        run: cmake -Snative -Bbuild -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release

      - name: Build CMake
        run: cmake --build build --config Release

      - name: Show directory tree
        shell: bash
        run: |
          find build/classes -print
          find build/REmatch-install -print

      - name: Java tests
        run: |
          mvn test
